version: "3.1"

services:
  simulator:
    container_name: simulator
    build:
      context: .
      dockerfile: Dockerfile
    # image: simulator
    networks:
      - proxynet
    environment:
      - MQTT=mqtt://mosquitto

networks:
  proxynet:
    name: kavanest-devnet
