version: "3.1"

services:
  simulator:
    container_name: kavanest-simulator
    image: kavanest-simulator
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxynet
    environment:
      - MQTT_LOCAL=mqtt://localhost

  mosquitto:
    image: eclipse-mosquitto:1.6
    container_name: kavanest-sim-mqtt
    expose:
      - 1883
      - 9001
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - proxynet

  kavanest-mongo:
    container_name: kavanest-mongo
    image: mongo
    networks:
      - proxynet
    # volumes:
    # - ./data:/data/db
    ports:
      - "27017:27017"

networks:
  proxynet:
    name: kavanest-devnet
