version: "3.5"
services:
  # kavanet-simulator:
  #   container_name: kavanet-simulator
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: kavanet-simulator:latest
  #   networks:
  #     - proxynet

  mosquitto:
    image: eclipse-mosquitto:1.6
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - 1883 # MQTT
      - 9001 # MQTT
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - proxynet

networks:
  proxynet:
    name: kavanet-network
