#* This file brings up the simulator, the MQTT broker and the mongo database
version: "3.1"

services:
  #* Comment out the simulator section below if you are dev'ing against
  #* the dockerised version of KavaNest
  simulator:
    container_name: kavanest-simulator
    image: kavanest-simulator
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxynet
    environment:
      - ENVIRONMENT=docker
      - MQTT_LIVE=mqtt://kavanet.io # For the sensor bridge connection
      - MQTT=mqtt://kavanest-mqtt

  mosquitto:
    image: eclipse-mosquitto:1.6
    container_name: kavanest-mqtt
    expose:
      - 1883
      - 9001
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - proxynet

  kavanest-mongo:
    container_name: kavanest-mongo
    image: mongo
    networks:
      - proxynet
    # volumes:
    # - ./data:/data/db
    ports:
      - "27017:27017"

networks:
  proxynet:
    name: kavanest-devnet
