name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: c5aad42327736fbe1b42bd873c76e820450832b8

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-simulator:test
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://192.168.1.46
