name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: 9e2c25a07c0bf0dbe27ea1007b773ddbb5f59830

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-test-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://192.168.1.46
