name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: dbeec593cb13cd67fab3ce0ac9a9707cd8bc414b

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://mqtt.kavanet.io
