name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: 97bf3a196f9f3a7ab0c66ec655c080a4e1071c82

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://mqtt.kavanet.io
