name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: 349874015a432c6de64aa615f19f19f9b33ee70f

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-simulator:test
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://192.168.1.46
