name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: 6e2a6dac8dd38b389be15771d2ff5a42e059be48

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-test-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://192.168.1.46
