name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: a59f5a4853ee403b0a36b6cac3d38874ba451f71

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-test-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://192.168.1.46
