name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: 5f3600d86a3a633a20ad22996fd08e651252f927

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://mqtt.kavanet.io
