name: kavanest-test-simulator

namespace: kavanest-test

deployment:
  - name: kavanest-test-simulator
    image: 192.168.1.61:5000/kavanest-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: ENVIRONMENT
        value: test

      - name: MQTT_TEST
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://192.168.1.46
