name: kavanest-test-simulator

namespace: kavanest-test

deployment:
  - name: kavanest-test-simulator
    image: 192.168.1.61:5000/kavanest-simulator:test
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://192.168.1.46

  - name: kavanest-test-mongo
    image: mongo:bionic
    ports:
    - port: 27017
    volumes:
    - type: pvc
      name: mongo-store
      path: /data/db

  - name: kavanest-test-mqtt
    image: eclipse-mosquitto:1.6
    ports:
    - port: 1883
    - port: 9001

pvc:
  - name: mongo-store
    storage: 100Mi

service:
  loadBalancer:
    - name: kavanest-test-mongo
      selector: kavanest-test-mongo
      port: 27017
      containerPort: 27017

    - name: kavanest-test-mqtt
      selector: kavanest-test-mqtt
      port: 1883
      containerPort: 1883
