name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: 6a02b5016de6cc52767e1481d5882a945b109ee2

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://mqtt.kavanet.io
