name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: 241e00693ff1dad1b1261b88f5e2260eeb8159e8

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-test-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://192.168.1.46
