name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: ce65db5dd4e191a5e7b44e2dcabb22e8d7a2d94e

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://mqtt.kavanet.io
