name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: 09a4786c6b2a91d093ded6047913dd7ad680e124

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://192.168.1.46
