name: kavanest-test-simulator

namespace: kavanest-test
env:
  APP_VERSION: ac9e2515d725f96886dafd455e55c7b5e4032ec8

deployment:
  - name: kavanest-test-simulator
    image: invisibug/kavanest-test-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: MQTT
        value: mqtt://kavanest-test-mqtt

      - name: MQTT_LIVE
        value: mqtt://192.168.1.46
