name: kavanest-simulator

namespace: kavanest

deployment:
  - name: mosquitto
    image: eclipse-mosquitto:1.6
    ports:
    - port: 1883
    - port: 9001

  - name: kavanest-simulator
    image: 192.168.1.61:5000/kavanest-simulator
    ports:
    - port: 1883
    - port: 9001
    env:
      - name: CLUSTER
        value: cluster
      - name: MQTT_LOCAL
        value: mqtt://localhost
      - name: MQTT_CLUSTER
        value: mqtt://mosquitto


service:
  clusterIP:
    - name: kavanest-simulator
      selector: mosquitto
      ports:
        - port: 1883
        - port: 9001
